### ISSUE TITLE
REST service returns Content-Type: text/html

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/FirstLook-REST#4]
This prevents some REST client tools from parsing the response intelligently.

I will submit a PR containing the (trivial) fix.

**Comment by gjsjohnmurray** [comment]
PR #5 

@JoshuaAGoldman any chance of a quick merge?

**Comment by isc-jgoldman** [comment]
Will do it as soon as I can check it on my laptop

Sent from my iPhone

On Sep 2, 2019, at 8:34 AM, John Murray <notifications@github.com<mailto:notifications@github.com>> wrote:


PR #5<https://github.com/intersystems/FirstLook-REST/pull/5>

@JoshuaAGoldman<https://github.com/JoshuaAGoldman> any chance of a quick merge?

**Comment by isc-jgoldman** [comment]
Done.

Thanks for the fix.
